apiVersion: apps/v1
kind: Deployment
metadata:
  name: azerothauctionassassin
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: azerothauctionassassin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azerothauctionassassin
  template:
    metadata:
      labels:
        app: azerothauctionassassin
    spec:
      containers:
        - name: azerothauctionassassin
          image: ghcr.io/vvanouytsel/azerothauctionasssassin:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: azerothauctionassassin-config
          
