apiVersion: apps/v1
kind: Deployment
metadata:
  name: azerothauctionassassin
  labels:
    app: azerothauctionassassin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azerothauctionassassin
  template:
    metadata:
      labels:
        app: azerothauctionassassin
    spec:
      containers:
        - name: azerothauctionassassin
          image: ghcr.io/vvanouytsel/azerothauctionassassin:latest
          imagePullPolicy: Always
          env:
            - name: MEGA_WEBHOOK_URL
              value: {{ .Values.megaWebhookUrl | quote }}
            - name: WOW_CLIENT_ID
              value: {{ .Values.wowClientId | quote }}
            - name: WOW_CLIENT_SECRET
              value: {{ .Values.wowClientSecret | quote }}
            - name: WOW_REGION
              value: "EU"
            - name: NO_RUSSIAN_REALMS
              value: "true"
            - name: DESIRED_ITEMS
              value: '{{ .Values.items | toJson }}'
